# Generated by Django 4.2.6 on 2023-11-22 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iacademy', '0004_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='gender',
            field=models.CharField(max_length=100),
        ),
    ]
