# Generated by Django 4.2.6 on 2023-12-18 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iacademy', '0009_staff_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_notification',
            name='status',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
